micronaut:
  application:
    name: student
netty:
  default:
    allocator:
      max-order: 3
graphql:
  graphiql:
    enabled: true
    version: 0.13.2
    path: /graphiql
    template-path: classpath:graphiql/index.html
    template-parameters:
    page-title: GraphiQL
